---
command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--hostname-strict=false"
  - "--http-port=8080"
  - "--spi-events-listener-jboss-logging-success-level=info"
  - "--spi-events-listener-jboss-logging-error-level=warn"

extraEnv: |
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: kc-admin-creds
        key: user
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kc-admin-creds
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:MaxRAMPercentage=50.0
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  - name: KC_DB_URL_HOST
    valueFrom:
      secretKeyRef:
        name: keycloak-db-app
        key: host
  - name: KC_DB_URL_PORT
    valueFrom:
      secretKeyRef:
        name: keycloak-db-app
        key: port
  - name: KC_DB_URL_DATABASE
    valueFrom:
      secretKeyRef:
        name: keycloak-db-app
        key: dbname
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-db-app
        key: username

database:
  vendor: postgres
  existingSecret: keycloak-db-app
  existingSecretKey: password

replicas: 3
