---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"

resources:
  - ./announcment.yaml
  - ./lbpool.yaml
  - ./gateway.yaml
