---
monitoring:
  enabled: true
  createPrometheusRules: true
toolbox:
  enabled: true
cephClusterSpec:
  cephConfig:
    global:
      bdev_enable_discard: "true"
      bdev_async_discard_threads: "1"
      osd_class_update_on_start: "false"
      device_failure_prediction_mode: local
  cleanupPolicy:
    wipeDevicesFromOtherClusters: true
  crashCollector:
    disable: false
  csi:
    readAffinity:
      enabled: false
  dashboard:
    enabled: false
  mgr:
    modules:
      - name: diskprediction_local
        enabled: true
      - name: insights
        enabled: true
      - name: pg_autoscaler
        enabled: true
      - name: rook
        enabled: true
  network:
    provider: host
    connections:
      requireMsgr2: true
  storage:
    useAllNodes: true
    useAllDevices: false
    devicePathFilter: /dev/disk/by-id/nvme-WD_Red_SN700_2000GB_.*
    config:
      osdsPerDevice: "1"
